---
- name: Wordpress | Apache | Copy virtual host configuration file
  template:
    src: apache-vhost.conf.j2
    dest: "/etc/httpd/conf.d/{{ wp_sitename }}.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
